# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "75452114cc9dbe46d2f057f243944c88"
name = "Countdown Timer"
application_url = "https://example.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,read_products,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
automatically_update_urls_on_dev = true
